<?php

return [
	'websitename'=>'Augodordesigns',
	'shopname'=>'Augodordesigns',
	'slogan'=>'Freshly baked with love every day!',
	'address'=>'Location: Ogbe Next to Havana Inn & Suites Hotel Ogwashi-Uku Aniocha South LGA Delta State Nigeria',
	'pagination' => 10,
	'passwordlength' => 5,
    'dateformat' => [
        'dmy' => 'd-m-Y h:i A',
        'slashdmy' => 'd/m/Y h:i A',
		'showtime' => 'H:i:s',
		'showtimeAMAPM' => 'h:i A',
		'showtimeAMANDPM' => 'H:i',
		'showdate' => 'd-m-Y',
		'datepicker' => 'Y-m-d',
		'dateTimepicker' => 'Y-m-d h:i',
		'dateTimepicker' => 'Y-m-d h:i',
		'slashdmyonly' => 'd/m/Y',
    ],
	'hbphone'=>'07034619334',
	'phonenumber'=>'09164978999',
	'emailcontact'=>'support@havanabakeryshop.com',
	'website'=>'www.havanabakeryshop.com',
	'address1'=>'3125 Maxwell Farm Road',
	'address2'=>'lagos Nigeria',
	'requisitionform'=>[
	'allowedDesignation'=>[10,7,2],
	],
	'floors'=>['1'=>'Ground Floor','First Floor','Second Floor','Third floor','Fouth Floor'],
	'genders'=>['1'=>'Male','2'=>'Female','3'=>'Other'],
	'locations'=>['1'=>'Main Hotel','2'=>'Extension','Other'],
	'identificationscard'=>['1'=>'National Identification Card','2'=>'National Passport','Work Identification','Driver`s Identification'],
	'salutations'=>['1'=>'Mr', 'Mrs', 'Miss', 'Ms', 'Chief', 'Dr', 'Lolo', 'Phd'],
	'type_of_guest'=> ['1'=>'Self','Company','Group'],
	'type_of_booking'=> ['1'=>'In-person','Online'],
	'method_of_payment' => ['2' => 'POS','3'=>'Bank Transfer'],
	'roomsdailysales' =>['heading'=>'Report Name : ','reportname'=>'Rooms Daily Sales Report'],
	'roomsavailability'=>['heading'=>'Report Name : ','reportname'=>'Rooms Availability Report'],
	'staffreport'=>['heading'=>'Report Name : ','reportname'=>'Staff Daily Sales Report'],
	
	
	'admin_Supervisor' => [1,2,10],
	'only_admin' => [1,2],
	'accessonlysuper_front_admin'=>[1,2,5,10],
	'menu_type'=>[10,11,12,14],
	'paymenttype'=>[1=>'Full Payment',2=>'Partial Payment'],
	'months'=>[1=>'January','Febuary','March','April','May','June','July','Auguest','September','October','November','December'],
	'attendancestartyear'=>2023,
	'ordertype' => [1=>'Regular','VIP'],
	'destinationto' =>['Pool Bar'=>'Pool Bar','VIP'=>'VIP','Bakery'=>'Bakery','Lounge'=>'Lounge','Kitchen'=>'Kitchen','Extension Bar'=>'Extension Bar','Others'=>'Others','Shawarma Stand'=>'Shawarma Stand'],
	'in_out_status' =>[2=>'In','Out','Damage','Delete from Warehouse','Delete from Requisition'],
	'warehouse_requisition_drink_details_listing'=>['heading'=>'','reportname'=>'Warehouse Requisition Drink Detail Report Listing'],
	'warehouse_requisition_food_details_listing'=>['heading'=>'','reportname'=>'Warehouse Requisition Food Detail Report Listing'],
	'warehouse_inventory_detailed_log'=>['heading'=>'','reportname'=>'Warehouse Inventory Detailed Log Report'],
	'local_storage'=>[1=>'Extension store #1','Main Hotel Store','Main Hotel Store Up Stair','Bakery Store','Extension store #2','Kitchen Store','Main and extension','Empty Drink Store','Dry room store','Equipment store #1','Equipment store #2','Pool Bar'],
	'stock_requisition_notes_report'=>['heading'=>'','reportname'=>'Stock Requisition Notes Report Listing'],
	'discount'=>[5=>'5%',10=>'10%',20=>'20%',30=>'30%',40=>'40%',50=>'50%'],
	'banquetbookingcontract'=>['heading'=>'','reportname'=>'Banquet Booking Contract'],
	'welcometohavana'=>['heading'=>'','reportname'=>'Welcome To Havana	Bakery Shop'],
	'Invoicepdf' => ['heading'=>'','reportname'=>'Guest Laundry Items'],
	'downloadorderpdf' => ['heading'=>'','reportname'=>'Order Listing'],
	'downloaddailyreportpdf' => ['heading'=>'','reportname'=>'Daily Inventory Report'],
	'damagelistpdf' => ['heading'=>'','reportname'=>'Damage Items Report'],
	'downloadstaffpdf' => ['heading'=>'','reportname'=>'Staff List'],
	'downloadproductwisereportpdf' => ['heading'=>'','reportname'=>'Staff List'],
	'downloadproductlistpdf' => ['heading'=>'','reportname'=>'Product List'],
	'downloadsubscriptionpdf' => ['heading'=>'','reportname'=>'Subscription List'],
	'downloadorderlistingpdf' => ['heading'=>'Order Listing Report','reportname'=>'Order Listing Report','filename'=>'Order-Listing-Report'],
	'inventoryMovementsPdf' => ['heading'=>'Transaction Report','reportname'=>'Transaction Report','filename'=>'Transaction Report'],
	'adjustmentMovementsPdf' => ['heading'=>'Adjustment Report','reportname'=>'Adjustment Report','filename'=>'Adjustment Report'],	
	'salespdf'=>['heading'=>'Sales Report','reportname'=>'Sales Report','filename'=>'Sales Report'],
	'downloaddaywisereportpdf' => ['heading'=>'Daily Sales Report','reportname'=>'Daily Sales Report','filename'=>'Daily Sales Report'],
	'downloaddailyStockSummaryPdf' => ['heading'=>'Daily Stock Report','reportname'=>'Daily Stock Report','filename'=>'Daily Stock Report'],
	'productSalesReportPdf' => ['heading'=>'	Product Sales Report','reportname'=>'	Product Sales Report','filename'=>'	Product Sales Report'],
	'customerOrdersPDF' => ['heading'=>'Customer Orders Report','reportname'=>'Customer Orders Report','filename'=>'	Customer Orders Report'],
	'stockPdf' => ['heading'=>'Stocks','reportname'=>'Stocks Report','filename'=>'Stocks Report'],
	'dispatchedanddeliveredPdf' => ['heading'=>'Dispatched & Delivered Orders','reportname'=>'Dispatched & Delivered Orders Report','filename'=>'Dispatched & Delivered Orders Reports'],
	'bulkofferspdf' => ['heading'=>'Bulk Offers Report','reportname'=>'Bulk Offers Report','filename'=>'Bulk Offers Report'],	
	'customerspdf' => ['heading'=>'Customer Report','reportname'=>'Customer Report','filename'=>'Customer Report'],	
	'productpdf' => ['heading'=>'Product Report','reportname'=>'Product Report','filename'=>'Product Report'],	
	'staffspdf' => ['heading'=>'Staff Report','reportname'=>'Staff Report','filename'=>'Staff Report'],		
	'categorypdf' => ['heading'=>'Categories Report','reportname'=>'Categories Report','filename'=>'Categories Report'],	
	'suffix' => ['Mr'=>'Mr','Mrs'=>'Mrs','Ms'=>'Ms',  'Miss'=>'Miss', 'Phd'=>'Phd', 'Dr'=>'Dr','Chief'=>'Chief', 'Sir'=>'Sir','Madama'=>'Madama','High Chief'=>'High Chief','Mazi'=>'Mazi','Nze'=>'Nze'],
	'emergecyRelationship' => [1 => 'Mother', 'Father', 'Husband', 'Wife', 'Son', 'Daughter', 'Sister', 'Brother', 'Other'],
	'staffstatus' => ['1'=>'Active','0'=>'Inactive', '2'=>'Resigned','3'=>'Fired','4'=>'Quit'],
	'accountstatus' => ['1'=>'Active','0'=>'Inactive'],
	'allowdigitbeforedecimal'=>'10',
	'allowafterdecimal'=>'3',
	'payment_way' => [1 => 'Full Payment', 'Partial Payment'],
	'order_status' => ['cancelled' => 'Cancelled','confirmed' => 'Confirmed', 'delivered' => 'Delivered', 'delivery-pending'=>'Delivery Pending','pending' => 'Pending'],
	'deliver_order_status' => ['delivered' => 'Delivered', 'delivery-pending'=>'Delivery Pending'],
	'payment_status' => ['pending' => 'Pending','completed' => 'Completed', 'cancelled' => 'Cancelled'],
	'customer_payment_method' => ['cash' => 'Cash','card' => 'Card', 'transfer' => 'Transfer'],
	'customer_order_status' => ['pending' => 'Pending','confirmed' => 'Confirmed', 'cancelled' => 'Cancelled'],
	'delivery_option'=>['Takeaway'=>'Takeaway','At Shop'=>'At Shop','Home Delivery'=>'Home Delivery','Curbside Pickup'=>'Curbside Pickup'],
	'transactiontype' => ['IN'=>'IN','OUT'=>'OUT'],
	// 'customerorderstatus'=>['pending' => 'Pending','confirmed' => 'Confirmed', 'cancelled' => 'Cancelled'],
];
